[profile.default]
test = 'test/solidity'
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 10000
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea73'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea73'
out = 'out'
fs_permissions = [
  { access = "read", path = "./deployments/" },
  { access = "read", path = "./config/" },
  { access = "read-write", path = "./test/logs/" },
]
ffi = true
libs = ["node_modules", "lib"]

[rpc_endpoints]
mainnet = "${ETH_NODE_URI_MAINNET}"
polygon = "${ETH_NODE_URI_POLYGON}"
bsc = "${ETH_NODE_URI_BSC}"
gnosis = "${ETH_NODE_URI_GNOSIS}"
fantom = "${ETH_NODE_URI_FANTOM}"
okx = "${ETH_NODE_URI_OKX}"
avalanche = "${ETH_NODE_URI_AVALANCHE}"
arbitrum = "${ETH_NODE_URI_ARBITRUM}"
optimism = "${ETH_NODE_URI_OPTIMISM}"
moonriver = "${ETH_NODE_URI_MOONRIVER}"
moonbeam = "${ETH_NODE_URI_MOONBEAM}"
celo = "${ETH_NODE_URI_CELO}"
fuse = "${ETH_NODE_URI_FUSE}"
cronos = "${ETH_NODE_URI_CRONOS}"
velas = "${ETH_NODE_URI_VELAS}"
harmony = "${ETH_NODE_URI_HARMONY}"
evmos = "${ETH_NODE_URI_EVMOS}"
aurora = "${ETH_NODE_URI_AURORA}"
linea = "${ETH_NODE_URI_LINEA}"
boba = "${ETH_NODE_URI_BOBA}"
nova = "${ETH_NODE_URI_NOVA}"
telos = "${ETH_NODE_URI_TELOS}"
zkSync = "${ETH_NODE_URI_ZKSYNC}"
zkSyncTestnet = "${ETH_NODE_URI_ZKSYNC_TESTNET}"
astar = "${ETH_NODE_URI_ASTAR}"
base = "${ETH_NODE_URI_BASE}"
pulse = "${ETH_NODE_URI_PULSE}"
zkEvm = "${ETH_NODE_URI_ZKEVM}"
mantle = "${ETH_NODE_URI_MANTLE}"
scroll = "${ETH_NODE_URI_SCROLL}"
manta = "${ETH_NODE_URI_MANTA}"
metis = "${ETH_NODE_URI_METIS}"
rootstock = "${ETH_NODE_URI_ROOTSTOCK}"
blast = "${ETH_NODE_URI_BLAST}"
horizen = "${ETH_NODE_URI_HORIZEN}"
kroma = "${ETH_NODE_URI_KROMA}"
merlin = "${ETH_NODE_URI_MERLIN}"
mode = "${ETH_NODE_URI_MODE}"
zkfair = "${ETH_NODE_URI_ZKFAIR}"
zklink = "${ETH_NODE_URI_ZKLINK}"
zetachain = "${ETH_NODE_URI_ZETACHAIN}"
xlayer = "${ETH_NODE_URI_XLAYER}"
taiko = "${ETH_NODE_URI_TAIKO}"
sei = "${ETH_NODE_URI_SEI}"
core = "${ETH_NODE_URI_CORE}"
testbera = "${ETH_NODE_URI_TESTBERA}"

# testnets
goerli = "${ETH_NODE_URI_GOERLI}"
mumbai = "${ETH_NODE_URI_MUMBAI}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
gnosis = { key = "${GNOSIS_ETHERSCAN_API_KEY}", url = "https://blockscout.com/poa/xdai/api" }
fantom = { key = "${FANTOM_ETHERSCAN_API_KEY}", url = "https://api.ftmscan.com/api" }
avalanche = { key = "${AVALANCHE_ETHERSCAN_API_KEY}", url = "https://api.snowtrace.io/api" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }
moonriver = { key = "${MOONRIVER_ETHERSCAN_API_KEY}", url = "https://api-moonriver.moonscan.io/api" }
moonbeam = { key = "${MOONBEAM_ETHERSCAN_API_KEY}", url = "https://api-moonbeam.moonscan.io/api" }
celo = { key = "${CELO_ETHERSCAN_API_KEY}", url = "https://explorer.celo.org/api" }
fuse = { key = "${FUSE_ETHERSCAN_API_KEY}", url = "https://explorer.fuse.io/api" }
cronos = { key = "${CRONOS_ETHERSCAN_API_KEY}", url = "https://api.cronoscan.com/api" }
aurora = { key = "${AURORA_ETHERSCAN_API_KEY}", url = "https://explorer.aurora.dev/api" }
boba = { key = "${BOBA_ETHERSCAN_API_KEY}", url = "https://api.bobascan.com/api" }
nova = { key = "${NOVA_ETHERSCAN_API_KEY}", url = "https://nova.arbiscan.io/api" }
astar = {key = "${ASTAR_ETHERSCAN_API_KEY}", url = "https://blockscout.com/astar/api"}
base = {key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api"}
pulse = {key = "${PULSE_ETHERSCAN_API_KEY}", url = "https://scan.pulsechain.com/api"}
polygon-zkevm = {key = "${ZKEVM_ETHERSCAN_API_KEY}", url = "https://api-zkevm.polygonscan.com/api"}
linea = {key = "${LINEA_ETHERSCAN_API_KEY}", url = "https://api.lineascan.build/api"}
mantle = {key = "${MANTLE_ETHERSCAN_API_KEY}", url = "https://explorer.mantle.xyz/api"}
scroll = {key = "${SCROLL_ETHERSCAN_API_KEY}", url = "https://blockscout.scroll.io/api"}
manta = {key = "${MANTA_ETHERSCAN_API_KEY}", url = "https://manta-pacific.calderaexplorer.xyz/api"}
metis = {key = "${METIS_ETHERSCAN_API_KEY}", url = "https://andromeda-explorer.metis.io/api"}
testbera = {key = "${TESTBERA_ETHERSCAN_API_KEY}", url = "https://scan-api.berachain-internal.com/api/"}

#testnets
goerli = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
mumbai = { key = "${MUMBAI_ETHERSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
